vm_url = "http://88.197.53.100:9090/mining/query/"

anova_url = vm_url + "ANOVA"
cart_url = vm_url + "CART"
histograms_url = vm_url + "HISTOGRAMS"
id3_url = vm_url + "ID3"
kmeans_url = vm_url + "KMEANS"
linear_regression_url = vm_url + "LINEAR_REGRESSION"
multiple_histograms_url = vm_url + "MULTIPLE_HISTOGRAMS"
cross_validation_url = vm_url + "CROSS_VALIDATION_K_FOLD"
naive_bayes_training_url = vm_url + "NAIVE_BAYES_TRAINING"
naive_bayes_testing_url = vm_url + "NAIVE_BAYES_TESTING"
naive_bayes_training_standalone_url = vm_url + "NAIVE_BAYES_TRAINING_STANDALONE"
ttest_independent_url = vm_url + "TTEST_INDEPENDENT"
ttest_onesample_url = vm_url + "TTEST_ONESAMPLE"
ttest_paired_url = vm_url + "TTEST_PAIRED"
