library(base)
library(jsonlite)
library(tidyverse)
library(data.table)

# Create simple coding contrasts
simpleCodingContrast <- function(variable) {
  levelsVar <- levels(variable)
  Nlevel <- length(levelsVar)
  contrastTreatment<-contr.treatment(Nlevel)
  contrast <- contrastTreatment - matrix(rep(1/Nlevel, Nlevel*(Nlevel-1)), ncol = Nlevel-1)
  rownames(contrast) <- levelsVar
  colnames(contrast) <-  levelsVar[-1]
  contrast
}


dummyCodingContrast <- function(variable) {
  levelsVar <- levels(variable)
  Nlevel <- length(levelsVar)
  contrastTreatment<-contr.treatment(Nlevel)
  contrast <- contrastTreatment
  rownames(contrast) <- levelsVar
  colnames(contrast) <-  levelsVar[-1]
  contrast
}

#Load data "desd-synthdata.csv" and check number of rows = 1000.
rawData <- read_csv("../unit_tests/datasets/CSVs/desd-synthdata.csv")

### Test 1.1: Test linear regression with one categorical regressor
df_LR11 <- rawData %>%
  select(
    lefthippocampus,
    alzheimerbroadcategory) %>%
  mutate(alzheimerbroadcategory = factor(alzheimerbroadcategory)) %>%
  mutate(alzheimerbroadcategory = relevel(alzheimerbroadcategory, ref = "AD")) %>%
  drop_na()
head(df_LR11)

#Analysis with dummy coding contrast
lmresult <- df_LR11 %>%
  lm(formula = lefthippocampus~alzheimerbroadcategory, contrasts = list(alzheimerbroadcategory = dummyCodingContrast(df_LR11$alzheimerbroadcategory)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= matrix(c("Test1.1.DC",ResultCoeff, ResultStats), ncol=3, byrow=TRUE, dimnames= list('',c("testname","ResultCoeff","ResultStats")))


#Analysis with simple coding contrast
lmresult <- df_LR11 %>%
  lm(formula = lefthippocampus~alzheimerbroadcategory, contrasts = list(alzheimerbroadcategory = simpleCodingContrast(df_LR11$alzheimerbroadcategory)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test1.1.SC", ResultCoeff, ResultStats))


##-----------------------------------------------------------------------------------------------------------
### Test 1.2: two categorical regressors without interaction
df_LR12 <- rawData %>%
  select(
    lefthippocampus,
    alzheimerbroadcategory,
    gender) %>%
  mutate(alzheimerbroadcategory = factor(alzheimerbroadcategory)) %>%
  mutate(alzheimerbroadcategory = relevel(alzheimerbroadcategory, ref = "AD")) %>%
  mutate(gender                 = factor(gender)) %>%
  mutate(gender                 = relevel(gender, ref = "M")) %>%
  drop_na()
head(df_LR12)

#Analysis with dummy coding contrast
lmresult <- df_LR12 %>%
lm(formula = lefthippocampus~ alzheimerbroadcategory + gender,
   contrasts = list(
     alzheimerbroadcategory = dummyCodingContrast(df_LR12$alzheimerbroadcategory),
     gender                 = dummyCodingContrast(df_LR12$gender)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test1.2.DC",ResultCoeff,ResultStats))


#Analysis with simple coding contrast
lmresult <- df_LR12 %>%
  lm(formula = lefthippocampus~ alzheimerbroadcategory + gender,
     contrasts = list(
       alzheimerbroadcategory = simpleCodingContrast(df_LR12$alzheimerbroadcategory),
       gender                 = simpleCodingContrast(df_LR12$gender)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test1.2.SC",ResultCoeff,ResultStats))



##-----------------------------------------------------------------------------------------------------------
### Test 1.2b: two categorical regressors with interaction
# Analysis with dummy coding contrast
lmresult <- df_LR12 %>%
  lm(formula = lefthippocampus~ alzheimerbroadcategory * gender,
     contrasts = list(
       alzheimerbroadcategory = dummyCodingContrast(df_LR12$alzheimerbroadcategory),
       gender                 = dummyCodingContrast(df_LR12$gender)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test1.2b.DC",ResultCoeff,ResultStats))


# Analysis with simple coding contrast
lmresult <- df_LR12 %>%
  lm(formula = lefthippocampus~ alzheimerbroadcategory * gender,
     contrasts = list(
       alzheimerbroadcategory = simpleCodingContrast(df_LR12$alzheimerbroadcategory),
       gender                 = simpleCodingContrast(df_LR12$gender)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test1.2b.SC",ResultCoeff,ResultStats))


##-----------------------------------------------------------------------------------------------------------
### Test 1.3: three categorical regressors without interaction
df_LR13 <- rawData %>%
  select(
    lefthippocampus,
    alzheimerbroadcategory,
    gender,
    agegroup) %>%
  mutate(alzheimerbroadcategory = factor(alzheimerbroadcategory)) %>%
  mutate(alzheimerbroadcategory = relevel(alzheimerbroadcategory, ref = "AD")) %>%
  mutate(gender                 = factor(gender)) %>%
  mutate(gender                 = relevel(gender, ref = "M")) %>%
  mutate(agegroup               = factor(agegroup)) %>%
  mutate(agegroup               = relevel(agegroup, ref = "+80y")) %>%
  drop_na()
head(df_LR13)

# Analysis with dummy coding contrast
lmresult <-df_LR13 %>%
  mutate(gender = relevel(gender, ref = "M")) %>%
  lm(formula = lefthippocampus~ alzheimerbroadcategory + gender + agegroup,
     contrasts = list(alzheimerbroadcategory = dummyCodingContrast(df_LR13$alzheimerbroadcategory),
                      gender = dummyCodingContrast(relevel(df_LR13$gender, ref = "M")),
                      agegroup = dummyCodingContrast(df_LR13$agegroup)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test1.3.DC",ResultCoeff,ResultStats))


# Analysis with simple coding contrast
lmresult <-df_LR13 %>%
  mutate(gender = relevel(gender, ref = "M")) %>%
  lm(formula = lefthippocampus~ alzheimerbroadcategory + gender + agegroup,
     contrasts = list(alzheimerbroadcategory = simpleCodingContrast(df_LR13$alzheimerbroadcategory),
                      gender = simpleCodingContrast(relevel(df_LR13$gender, ref = "M")),
                      agegroup = simpleCodingContrast(df_LR13$agegroup)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test1.3.SC",ResultCoeff,ResultStats))



### Test 1.3b: three categorical regressors with all interactions
# Analysis with dummy coding contrast
lmresult <-df_LR13 %>%
  mutate(gender = relevel(gender, ref = "M")) %>%
  lm(formula = lefthippocampus~ alzheimerbroadcategory * gender * agegroup,
     contrasts = list(alzheimerbroadcategory = dummyCodingContrast(df_LR13$alzheimerbroadcategory),
                      gender = dummyCodingContrast(relevel(df_LR13$gender, ref = "M")),
                      agegroup = dummyCodingContrast(df_LR13$agegroup)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test1.3b.DC",ResultCoeff,ResultStats))



# Analysis with simple coding contrast
lmresult <-df_LR13 %>%
  mutate(gender = relevel(gender, ref = "M")) %>%
  lm(formula = lefthippocampus~ alzheimerbroadcategory * gender * agegroup,
     contrasts = list(alzheimerbroadcategory = simpleCodingContrast(df_LR13$alzheimerbroadcategory),
                      gender = simpleCodingContrast(relevel(df_LR13$gender, ref = "M")),
                      agegroup = simpleCodingContrast(df_LR13$agegroup)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test1.3b.SC",ResultCoeff,ResultStats))



##-------------------------------------------------------------------------------------------------------------------------
## Test linear regression with continuous regressors
### Test 2.1: one continuous regressor
df_LR21 <- rawData %>%
  select(
    lefthippocampus,
    csfglobal) %>%
  drop_na()
head(df_LR21)

lmresult <-df_LR21 %>%
  lm(formula = lefthippocampus ~ csfglobal)
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test2.1",ResultCoeff,ResultStats))



### Test 2.2: two continuous regressors without interaction
df_LR22 <- rawData %>%
  select(
    lefthippocampus,
    opticchiasm,
    minimentalstate) %>%
  drop_na()
head(df_LR22)

lmresult <-df_LR22 %>%
  lm(formula = lefthippocampus ~ opticchiasm + minimentalstate)
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test2.2",ResultCoeff,ResultStats))



### Test 2.2b: two continuous regressors with interaction
lmresult <-df_LR22 %>%
  lm(formula = lefthippocampus ~ opticchiasm * minimentalstate)
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test2.2b",ResultCoeff,ResultStats))



### Test 2.3: three continuous regressors without interaction
df_LR23 <- rawData %>%
  select(
    lefthippocampus,
    opticchiasm,
    minimentalstate,
    subjectage) %>%
  drop_na()
head(df_LR23)

lmresult <-df_LR23 %>%
  lm(formula = lefthippocampus ~ opticchiasm + minimentalstate + subjectage)
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test2.3",ResultCoeff,ResultStats))



### Test 2.3b: three continuous regressors with interaction
lmresult <-df_LR23 %>%
  lm(formula = lefthippocampus ~ opticchiasm * minimentalstate * subjectage)
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test2.3b",ResultCoeff,ResultStats))



##------------------------------------------------------------------------------------------------------------------------------------------------------------
## Test linear regression with mixted categorical and continuous regressors
### Test 3.1: one categorical and one continuous regressors without interaction
df_LR31 <- rawData %>%
  select(
    lefthippocampus,
    alzheimerbroadcategory,
    subjectage) %>%
  mutate(alzheimerbroadcategory = factor(alzheimerbroadcategory)) %>%
  mutate(alzheimerbroadcategory = relevel(alzheimerbroadcategory, ref = "AD")) %>%
  drop_na()
head(df_LR31)

#Analysis with dummy coding contrast
lmresult <- df_LR31 %>%
  lm(formula = lefthippocampus~ alzheimerbroadcategory + subjectage,
     contrasts = list(
       alzheimerbroadcategory = dummyCodingContrast(df_LR31$alzheimerbroadcategory)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.1.DC",ResultCoeff,ResultStats))


# Analysis with simple coding contrast
lmresult <- df_LR31 %>%
  lm(formula = lefthippocampus~ alzheimerbroadcategory + subjectage,
     contrasts = list(
       alzheimerbroadcategory = simpleCodingContrast(df_LR31$alzheimerbroadcategory)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.1.SC",ResultCoeff,ResultStats))


### Test 3.1b: one categorical and one continuous regressors with interaction
# Analysis with dummy coding contrast
lmresult <- df_LR31 %>%
  lm(formula = lefthippocampus~ alzheimerbroadcategory * subjectage,
     contrasts = list(
       alzheimerbroadcategory = dummyCodingContrast(df_LR31$alzheimerbroadcategory)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.1b.DC",ResultCoeff,ResultStats))

#Analysis with simple coding contrast
lmresult <- df_LR31 %>%
  lm(formula = lefthippocampus~ alzheimerbroadcategory * subjectage,
     contrasts = list(
       alzheimerbroadcategory = simpleCodingContrast(df_LR31$alzheimerbroadcategory)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.1b.SC",ResultCoeff,ResultStats))


### Test 3.2: one categorical and two continuous regressors without interaction
df_LR32 <- rawData %>%
  select(
    lefthippocampus,
    alzheimerbroadcategory,
    subjectage,
    opticchiasm) %>%
  mutate(alzheimerbroadcategory = factor(alzheimerbroadcategory)) %>%
  mutate(alzheimerbroadcategory = relevel(alzheimerbroadcategory, ref = "AD")) %>%
  drop_na()
head(df_LR32)

# Analysis with dummy coding contrast
lmresult <- df_LR32 %>%
  lm(formula = lefthippocampus ~ alzheimerbroadcategory + subjectage + opticchiasm,
     contrasts = list(
       alzheimerbroadcategory = dummyCodingContrast(df_LR31$alzheimerbroadcategory)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.2.DC",ResultCoeff,ResultStats))


# Analysis with simple coding contrast
lmresult <- df_LR32 %>%
  lm(formula = lefthippocampus ~ alzheimerbroadcategory + subjectage + opticchiasm,
     contrasts = list(
       alzheimerbroadcategory = simpleCodingContrast(df_LR31$alzheimerbroadcategory)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.2.SC",ResultCoeff,ResultStats))


### Test 3.2b: one categorical and two continuous regressors with interaction
# Analysis with dummy coding contrast
lmresult <- df_LR32 %>%
  lm(formula = lefthippocampus ~ alzheimerbroadcategory * subjectage * opticchiasm,
     contrasts = list(
       alzheimerbroadcategory = dummyCodingContrast(df_LR31$alzheimerbroadcategory)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.2b.DC",ResultCoeff,ResultStats))


# Analysis with simple coding contrast
lmresult <- df_LR32 %>%
  lm(formula = lefthippocampus ~ alzheimerbroadcategory * subjectage * opticchiasm,
     contrasts = list(
       alzheimerbroadcategory = simpleCodingContrast(df_LR31$alzheimerbroadcategory)))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.2b.SC",ResultCoeff,ResultStats))

### Test 3.3: two categorical and one continuous regressors without interaction
df_LR33 <- rawData %>%
  select(
    lefthippocampus,
    alzheimerbroadcategory,
    subjectage,
    gender) %>%
  mutate(alzheimerbroadcategory = factor(alzheimerbroadcategory)) %>%
  mutate(alzheimerbroadcategory = relevel(alzheimerbroadcategory, ref = "AD")) %>%
  mutate(gender                 = factor(gender)) %>%
  mutate(gender                 = relevel(gender, ref = "M")) %>%
  drop_na()
head(df_LR33)


# Analysis with dummy coding contrast
lmresult <- df_LR33 %>%
  lm(formula = lefthippocampus ~ alzheimerbroadcategory + gender + subjectage,
     contrasts = list(
       alzheimerbroadcategory = dummyCodingContrast(df_LR31$alzheimerbroadcategory),
       gender                 = dummyCodingContrast(relevel(df_LR33$gender, ref = "M"))))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.3.DC",ResultCoeff,ResultStats))


#Analysis with simple coding contrast
lmresult <- df_LR33 %>%
  lm(formula = lefthippocampus ~ alzheimerbroadcategory + gender + subjectage,
     contrasts = list(
       alzheimerbroadcategory = simpleCodingContrast(df_LR31$alzheimerbroadcategory),
       gender                 = simpleCodingContrast(relevel(df_LR33$gender, ref = "M"))))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.2.3.SC",ResultCoeff,ResultStats))


### Test 3.3b: two categorical and one continuous regressors with interaction
# Analysis with dummy coding contrast
lmresult <- df_LR33 %>%
  lm(formula = lefthippocampus ~ alzheimerbroadcategory * gender * subjectage,
     contrasts = list(
       alzheimerbroadcategory = dummyCodingContrast(df_LR31$alzheimerbroadcategory),
       gender                 = dummyCodingContrast(relevel(df_LR33$gender, ref = "M"))))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.3b.DC",ResultCoeff,ResultStats))


# Analysis with simple coding contrast
lmresult <- df_LR33 %>%
  lm(formula = lefthippocampus ~ alzheimerbroadcategory * gender * subjectage,
     contrasts = list(
       alzheimerbroadcategory = simpleCodingContrast(df_LR31$alzheimerbroadcategory),
       gender                 = simpleCodingContrast(relevel(df_LR33$gender, ref = "M"))))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.3b.SC",ResultCoeff,ResultStats))

### Test 3.4: two categorical and two continuous regressors without interaction
df_LR34 <- rawData %>%
  select(
    lefthippocampus,
    alzheimerbroadcategory,
    brainstem,
    opticchiasm,
    gender) %>%
  mutate(alzheimerbroadcategory = factor(alzheimerbroadcategory)) %>%
  mutate(alzheimerbroadcategory = relevel(alzheimerbroadcategory, ref = "AD")) %>%
  mutate(gender                 = factor(gender)) %>%
  mutate(gender                 = relevel(gender, ref = "M")) %>%
  drop_na()
head(df_LR34)


# Analysis with dummy coding contrast
lmresult <- df_LR34 %>%
  lm(formula = lefthippocampus ~ alzheimerbroadcategory + gender + brainstem + opticchiasm,
     contrasts = list(
       alzheimerbroadcategory = dummyCodingContrast(df_LR31$alzheimerbroadcategory),
       gender                 = dummyCodingContrast(relevel(df_LR33$gender, ref = "M"))))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.4.DC",ResultCoeff,ResultStats))


# Analysis with simple coding contrast
lmresult <- df_LR34 %>%
  lm(formula = lefthippocampus ~ alzheimerbroadcategory + gender + brainstem + opticchiasm,
     contrasts = list(
       alzheimerbroadcategory = simpleCodingContrast(df_LR31$alzheimerbroadcategory),
       gender                 = simpleCodingContrast(relevel(df_LR33$gender, ref = "M"))))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.4.SC",ResultCoeff,ResultStats))


### Test 3.4b: two categorical and two continuous regressors with interaction
# Analysis with dummy coding contrast
lmresult <- df_LR34 %>%
  lm(formula = lefthippocampus ~ alzheimerbroadcategory * gender * brainstem * opticchiasm,
     contrasts = list(
       alzheimerbroadcategory = dummyCodingContrast(df_LR31$alzheimerbroadcategory),
       gender                 = dummyCodingContrast(relevel(df_LR33$gender, ref = "M"))))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.4b.DC",ResultCoeff,ResultStats))


# Analysis with simple coding contrast
lmresult <- df_LR34 %>%
  lm(formula = lefthippocampus ~ alzheimerbroadcategory * gender * brainstem * opticchiasm,
     contrasts = list(
       alzheimerbroadcategory = simpleCodingContrast(df_LR31$alzheimerbroadcategory),
       gender                 = simpleCodingContrast(relevel(df_LR33$gender, ref = "M"))))
ResultCoeff <-toJSON(as.data.table(summary(lmresult)$coefficients, keep.rownames=TRUE))
ResultStats<- toJSON(as.data.table( matrix( c(summary(lmresult)$sigma, summary(lmresult)$df[2], summary(lmresult)$r.squared, summary(lmresult)$adj.r.squared,
                        summary(lmresult)$fstatistic[1], summary(lmresult)$fstatistic[2], min(summary(lmresult)$residuals), max(summary(lmresult)$residuals)),
                        ncol=8,byrow=TRUE,
                        dimnames = list ('',c("sigma","df", "r_squared", "adj_r_squared", "fstatistic","numdf", "minresiduals","maxresiduals")))))
TotalResult= rbind(TotalResult, c("Test3.4b.SC",ResultCoeff,ResultStats))


return (toJSON(TotalResult))
