
library(base)
library(jsonlite)
library(tidyverse)
library(jmv)

df_TT <- read_csv("../unit_tests/data/dementia/CSVs/desd-synthdata.csv",
    col_types = cols(gender = col_factor(levels = c("M","F"))))


## Comparison with a reference value
#In this test, we compare the mean of the left and right hippocampus #volumes separetely, with a reference value 3.


Result <- ttestOneS(
  data = df_TT,
  vars = vars(lefthippocampus, righthippocampus),
  testValue = 3.0,
  hypothesis = 'lt',
  effectSize = T ,
  ci = T,
  meanDiff = T)

Test1Result <- toJSON(Result$ttest$asDF, na="string")


Result <- ttestOneS(
  data = df_TT,
  vars = vars(lefthippocampus, righthippocampus),
  testValue = 3.0,
  hypothesis = 'dt',
  effectSize = T ,
  ci = T,
  meanDiff = T)
Test2Result <- toJSON(Result$ttest$asDF, na="string")

Result <- ttestOneS(
  data = df_TT,
  vars = vars(lefthippocampus, righthippocampus),
  testValue = 3.0,
  hypothesis = 'gt',
  effectSize = T ,
  ci = T,
  meanDiff = T)
Test3Result <- toJSON(Result$ttest$asDF, na="string")

Result <- ttestOneS(
  data = df_TT,
  vars = vars(lefthippocampus, righthippocampus),
  testValue = 3.0,
  hypothesis = 'dt',
  effectSize = T ,
  ci = T,
  meanDiff = T)
Test4Result <- toJSON(Result$ttest$asDF, na="string")

return(c(Test1Result, Test2Result, Test3Result, Test4Result))
