
library(base)
library(jsonlite)
library(tidyverse)
library(jmv)

df_TT <- read_csv("../unit_tests/data/dementia/desd-synthdata.csv",
                  col_types = cols(gender = col_factor(levels = c("M", "F"))))

## Test #1: independent samples T-Test
# In this test, we want to know if the volume of the female's left hippocampus is different from that of the male.
#We check if the means are different.

Result = ttestIS(
  formula = lefthippocampus ~ gender,
  data = df_TT,
  hypothesis = 'different',
  effectSize = T,
  ci = T,
  meanDiff = T
  )
Test1aResult <- toJSON(Result$ttest$asDF, na="string")


Result = ttestIS(
  formula = lefthippocampus ~ gender,
  data = df_TT,
  hypothesis = 'different',
  effectSize = T,
  ci = T,
  meanDiff = T
  )
Test1bResult <- toJSON(Result$ttest$asDF, na="string")

#We check if the mean volumes are greater for men than for women.
Result = ttestIS(
  formula = lefthippocampus ~ gender,
  data = df_TT,
  hypothesis = 'oneGreater',
  meanDiff = T,
  ci = T,
  effectSize = T
  )
Test2Result <- toJSON(Result$ttest$asDF, na="string")

#We check if the mean volumes are greater for men than for women.
Result = ttestIS(
  formula = lefthippocampus ~ gender,
  data = df_TT,
  hypothesis = 'twoGreater',
  meanDiff = T,
  ci = T,
  effectSize = T
  )
Test3Result <- toJSON(Result$ttest$asDF, na="string")

return(c(Test1aResult, Test1bResult, Test2Result, Test3Result))
