---
- hosts: master
  name: Initialize Docker Swarm
  remote_user: "{{ hostvars['master']['remote_user'] }}"
  become: yes
  become_user: "{{ hostvars['master']['become_user'] }}"
  roles:
   - swarm-init
   - add-label
   - copy-directory