---
- hosts: master
  name: Copy Metadata File To Master
  remote_user: "{{ hostvars['master']['remote_user'] }}"
  become: yes
  become_user: "{{ hostvars['master']['become_user'] }}"
  roles:
   - copy-metadata