---
- hosts: master
  name: Start Services
  remote_user: "{{ hostvars['master']['remote_user'] }}"
  become: yes
  become_user: "{{ hostvars['master']['become_user'] }}"
  vars_files:
    - group_vars/exareme.yaml
  roles:
   - copy-directory
   - start-services
