# coding: utf-8


stopwords=set([ur".", ur"_", ur"stessi", ur"można", ur"einseitiger", ur"wären", ur"fÛr", ur"olette", ur"würde", ur"andre", ur"για", ur"ebben", ur"negl", ur"steigen", ur"einseitigen",
ur"dere", ur"niissä", ur"ergänzen", ur"otro", ur"noista", ur"dazu", ur"περί", ur"tobie", ur"erst", ur"mußt", ur"szinte", ur"otra", ur"drauf", ur"gänzlich", ur"aus",
ur"under", ur"aux", ur"gesehen", ur"shouldn't", ur"dela", ur"neun", ur"dele", ur"berichteten", ur"neue", ur"voie", ur"ayantes", ur"letztes", ur"vase", ur"staremo",
ur"algunos", ur"letzten", ur"tandis", ur"tinham", ur"senin", ur"olisimme", ur"we'll", ur"ÔÏÇÏ", ur"mog±", ur"haben", ur"zde", ur"geworden", ur"zda", ur"upp",
ur"teníais", ur"fuera", ur"esos", ur"zuletzt", ur"abbiate", ur"zonder", ur"hors", ur"fece", ur"angefangen", ur"varit", ur"ezt", ur"verrate", ur"n",
ur"ellas", ur"alt", ur"avrebbero", ur"nel", ur"nem", ur"ÍÏÖÎÏ", ur"tipo", ur"nei", ur"emilyen", ur"ned", ur"klaren", ur"while", ur"ebbe", ur"tipy", ur"kun",
ur"estuvo", ur"nez", ur"sobre", ur"farebbero", ur"estuve", ur"ekkor", ur"fall", ur"neu", ur"nes", ur"dahi", ur"med", ur"meg", ur"powinni", ur"powinno", ur"daha",
ur"derjenige", ur"wezen", ur"men", ur"flere", ur"here", ur"meu", ur"met", ur"nicht", ur"avere", ur"mes", ur"mer", ur"hers", ur"ungefähr", ur"amolyan", ur"schätzt",
ur"sidan", ur"même", ur"gli", ur"auf", ur"ÓÅÊÞÁÓ", ur"anstatt", ur"näiksi", ur"aki", ur"i'd", ur"ueber", ur"där", ur"i'm", ur"aurai", ur"kýrk", ur"müssten", ur"esteve",
ur"arról", ur"desselben", ur"także", ur"magst", ur"कोई", ur"outro", ur"जो", ur"bra", ur"sarai", ur"tels", ur"estive", ur"would", ur"heille", ur"einiger",
ur"einiges", ur"fussions", ur"loro", ur"seraient", ur"vermögen", ur"cali", ur"niiden", ur"einigem", ur"ellos", ur"उसके", ur"sembra", ur"właśnie", ur"által", ur"willst",
ur"Á", ur"sabeu", ur"musi", ur"wenig", ur"saber", ur"sabes", ur"किया", ur"tendrías", ur"herein", ur"wohingegen", ur"facemmo", ur"nigdy", ur"ÔÏÖÅ", ur"ια", ur"sabem",
ur"saben", ur"quale", ur"me", ur"×ÅÄØ", ur"olet", ur"solament", ur"ma", ur"जा", ur"weiteres", ur"weiterer", ur"mi", ur"maiorias", ur"ने", ur"mu", ur"ÍÏÊ", ur"weiterem",
ur"era", ur"ÂÙÌÁ", ur"weiteren", ur"olen", ur"której", ur"जब", ur"ero", ur"my", ur"avaient", ur"wieviel", ur"czy", ur"étiez", ur"jest", ur"tuvieses", ur"czemu",
ur"consigue", ur"who's", ur"gegen", ur"wann", ur"tuoksi", ur"tuvierais", ur"auraient", ur"geben", ur"ambos", ur"wirklich", ur"want", ur"ना", ur"muesste", ur"hundert",
ur"újra", ur"buna", ur"anderes", ur"hoe", ur"end", ur"ene", ur"weiterhin", ur"czyli", ur"przy", ur"woraufhin", ur"off", ur"enn", ur"algmas", ur"startete", ur"how",
ur"ens", ur"bunu", ur"hos", ur"wenige", ur"stille", ur"anderen", ur"doesn't", ur"jsme", ur"mÅ", ur"facesti", ur"vocês", ur"ÈÏÒÏÛÏ", ur"sanki", ur"lag", ur"hubierais",
ur"mest", ur"वर्ग", ur"kimś", ur"Ö", ur"lat", ur"sería", ur"lav", ur"mogą", ur"las", ur"senkte", ur"gdyż", ur"je¶li", ur"mí", ur"estem", ur"cinque", ur"hasta",
ur"getragen", ur"letztlich", ur"reagiere", ur"mý", ur"sont", ur"stettero", ur"vart", ur"बहुत", ur"josta", ur"vars", ur"aient", ur"over", ur"zei", ur"teniu", ur"peut",
ur"hubiese", ur"nostra", ur"vara", ur"nostre", ur"ezzel", ur"nostri", ur"वे", ur"avevo", ur"vite", ur"nostro", ur"úgy", ur"begge", ur"gente", ur"bisher", ur"bundan",
ur"übel", ur"hon", ur"vilken", ur"rá", ur"valor", ur"teilen", ur"minden", ur"fin", ur"dorthin", ur"fim", ur"then", ur"them", ur"sinulta", ur"keissä", ur"deinem",
ur"deinen", ur"plötzlich", ur"deines", ur"deiner", ur"bana", ur"they", ur"mucho", ur"pelas", ur"wenn", ur"mindestens", ur"ausser", ur"nawet", ur"hubieran", ur"worden",
ur"dinge", ur"l", ur"estaréis", ur"até", ur"Õ", ur"ÌÕÞÛÅ", ur"each", ur"ενός", ur"ihn", ur"akkor", ur"verriet", ur"kterou", ur"diye", ur"darüberhinaus", ur"mają",
ur"बाद", ur"estivermos", ur"nokon", ur"navn", ur"autre", ur"mikor", ur"zahlreich", ur"deira", ur"findest", ur"nötigenfalls", ur"aurais", ur"aurait", ur"deverá",
ur"behielt", ur"begann", ur"hätte", ur"sang", ur"god", ur"diesem", ur"diesen", ur"slutt", ur"re", ur"dieser", ur"dieses", ur"suyas", ur"werde", ur"avoir",
ur"geteilt", ur"frei", ur"nirgends", ur"verdadero", ur"icke", ur"verdadera", ur"consegueixo", ur"ÚÁ", ur"więc", ur"doppelt", ur"elle", ur"brauchen", ur"weniger",
ur"inom", ur"hennar", ur"ÓËÁÚÁÔØ", ur"einführte", ur"legen", ur"intentan", ur"bár", ur"çünkü", ur"versorgten", ur"birkaç", ur"estas", ur"dahin", ur"ist", ur"att",
ur"eramos", ur"bräuchte", ur"solch", ur"gehabt", ur"podemos", ur"staranno", ur"intentas", ur"intentar", ur"einer", ur"eines", ur"serei", ur"avrebbe", ur"näitä",
ur"minä", ur"esté", ur"ÂÅÚ", ur"näissä", ur"tuon", ur"einen", ur"für", ur"hogyan", ur"ÔÏÇÄÁ", ur"unmöglicher", ur"drunter", ur"peggio", ur"τον", ur"är",
ur"perquè", ur"ingen", ur"tot", ur"estuvieseis", ur"brachten", ur"quinto", ur"toi", ur"ton", ur"solamente", ur"tom", ur"tuossa", ur"doppio", ur"ganze",
ur"beitrugen", ur"seré", ur"llarg", ur"beides", ur"poderá", ur"estavam", ur"nahm", ur"beiden", ur"του", ur"ależ", ur"verte", ur"både", ur"vielen", ur"sille",
ur"teiltä", ur"dürfen", ur"minua", ur"houve", ur"verraten", ur"kto", ur"hemos", ur"ancora", ur"sta", ur"vieles", ur"vieler", ur"sekä", ur"sposób", ur"yirmi",
ur"este", ur"esta", ur"jederlei", ur"nehmen", ur"durchaus", ur"esto", ur"mine", ur"vagyok", ur"korso", ur"jeres", ur"már", ur"further", ur"eröffnetes", ur"vorüber",
ur"häneltä", ur"habrás", ur"mint", ur"künftig", ur"niçin", ur"birþey", ur"fosti", ur"degl", ur"foste", ur"alors", ur"altri", ur"deres", ur"derer", ur"ÌÉ", ur"deren",
ur"derem", ur"feci", ur"tym", ur"eût", ur"oltre", ur"inzwischen", ur"dafür", ur"tylko", ur"ohne", ur"erano", ur"meidät", ur"doit", ur"ÂÙÌ", ur"état", ur"meidän",
ur"dois", ur"ihres", ur"sarò", ur"nämlich", ur"γι", ur"fusse", ur"avranno", ur"ahhoz", ur"hanno", ur"seks", ur"cała", ur"m", ur"dog", ur"noihin", ur"cały", ur"mithin",
ur"dos", ur"dov", ur"yani", ur"singen", ur"tuolta", ur"tatsächlich", ur"hur", ur"muß", ur"estais", ur"sage", ur"liest", ur"ebbi", ur"én", ur"nélkül", ur"sagt",
ur"somt", ur"och", ur"wirst", ur"egyetlen", ur"dessen", ur"henne", ur"höchstens", ur"danach", ur"sarebbero", ur"sto", ur"किसी", ur"daher", ur"estadas", ur"sien",
ur"sehen", ur"irá", ur"avrete", ur"nebenan", ur"do", ur"meget", ur"gdzieś", ur"above", ur"klein", ur"di", ur"de", ur"stor", ur"da", ur"geen", ur"vsak", ur"du",
ur"einmal", ur"rispetto", ur"ikkje", ur"furent", ur"außerhalb", ur"stiamo", ur"anfangen", ur"των", ur"nämä", ur"rund", ur"nichts", ur"tenías", ur"estados", ur"iets",
ur"gjÛre", ur"starei", ur"blev", ur"iż", ur"dort", ur"ÚÄÅÓØ", ur"skulle", ur"tenham", ur"nur", ur"inny", ur"nun", ur"gefällt", ur"inne", ur"faig",
ur"machst", ur"inna", ur"schreiben", ur"iemand", ur"amikor", ur"blei", ur"inni", ur"eres", ur"staremmo", ur"houvéssemos", ur"weiter", ur"bekannt", ur"wogegen",
ur"bien", ur"estiveram", ur"ÔÅÐÅÒØ", ur"erhalten", ur"आप", ur"eren", ur"którego", ur"erem", ur"habrían", ur"we", ur"powinna", ur"welche", ur"legyen", ur"diese",
ur"wo", ur"soyons", ur"were", ur"anche", ur"sagten", ur"legten", ur"hätt", ur"stiegen", ur"niż", ur"möglicherweise", ur"ezen", ur"direkter", ur"ÖÉÚÎØ", ur"drei",
ur"ile", ur"questa", ur"clanku", ur"mancherorts", ur"ËÁË", ur"estuviera", ur"clanky", ur"coz", ur"questi", ur"against", ur"genug", ur"una", ur"kommer", ur"und",
ur"ils", ur"då", ur"coi", ur"vorher", ur"com", ur"col", ur"con", ur"habían", ur"foram", ur"vaig", ur"tovább", ur"elf", ur"jakaś", ur"durante", ur"niye",
ur"befragen", ur"ni¿", ur"vais", ur"ÜÔÉ", ur"ele", ur"habías", ur"podria", ur"fra", ur"aren't", ur"हैं", ur"tendrás", ur"tuolla", ur"been", ur"estaban", ur"estabas",
ur"tinc", ur"toen", ur"tenemos", ur"joiden", ur"jolta", ur"amelyekben", ur"jossa", ur"nagyon", ur"tendré", ur"i¿", ur"बनी", ur"pueden", ur"zich", ur"मे", ur"olisit",
ur"hvilken", ur"stavano", ur"suas", ur"mivel", ur"könnt", ur"letztendlich", ur"avessimo", ur"keistä", ur"aqueles", ur"auras", ur"þey", ur"ait", ur"avrei", ur"ayants",
ur"podriais", ur"egyik", ur"dello", ur"miltä", ur"serai", ur"ÎÉÂÕÄØ", ur"vagy", ur"aie", ur"delle", ur"della", ur"faremmo", ur"unos", ur"pokud", ur"unwichtig",
ur"indietro", ur"tässä", ur"is", ur"ir", ur"it", ur"desto", ur"estos", ur"ik", ur"im", ur"il", ur"io", ur"in", ur"dedans", ur"if", ur"quand", ur"meitä", ur"manchem",
ur"manchen", ur"manches", ur"mancher", ur"quant", ur"nokor", ur"tätä", ur"makt", ur"än", ur"angesetze", ur"elli", ur"keressünk", ur"manche", ur"gekonnt", ur"nim",
ur"nic", ur"coś", ur"jetzt", ur"nie", ur"angesetzt", ur"elõtt", ur"sollt", ur"hayan", ur"kim", ur"ells", ur"kvarhelst", ur"ÍÎÏÇÏ", ur"depois", ur"he'll", ur"hacer",
ur"haces", ur"ihrem", ur"singt", ur"ihren", ur"tienes", ur"algun", ur"ÔÅÂÑ", ur"gekommen", ur"suyo", ur"drin", ur"enhver", ur"thi", ur"twój", ur"folgendes", ur"the",
ur"ihrer", ur"hacen", ur"yours", ur"jeszcze", ur"andere", ur"she'll", ur"denen", ur"anderm", ur"andern", ur"करने", ur"mientras", ur"था", ur"fueseis", ur"anderr",
ur"anders", ur"veja", ur"eus", ur"farei", ur"hai", ur"antes", ur"ausdrückt", ur"ham", ur"han", ur"kell", ur"vollständig", ur"hab", ur"ela", ur"had", ur"estuvieron",
ur"conseguimos", ur"hay", ur"niemals", ur"ÜÔÏÇÏ", ur"els", ur"har", ur"has", ur"hat", ur"zou", ur"opp", ur"trägt", ur"उनकी", ur"unter", ur"gewollt", ur"dessa",
ur"zurück", ur"unten", ur"ένα", ur"mille", ur"étantes", ur"között", ur"stavate", ur"również", ur"gemocht", ur"थे", ur"mykje", ur"थी", ur"näiden",
ur"की", ur"वाले", ur"करना", ur"ËÁÖÅÔÓÑ", ur"szemben", ur"ole", ur"kunne", ur"oli", ur"bort", ur"teria", ur"meer", ur"facendo", ur"habéis", ur"tendríamos",
ur"miêdzy", ur"seja", ur"vårt", ur"ici", ur"ich", ur"consiguen", ur"for", ur"sota", ur"bizi", ur"ÂÕÄÅÔ", ur"valaki", ur"może", ur"reagieren", ur"muito", ur"olisin",
ur"uma", ur"seríamos", ur"tuviese", ur"consigues", ur"müßt", ur"ÜÔÏÊ", ur"foi", ur"elõ", ur"annak", ur"unse", ur"who", ur"इसी", ur"encima", ur"tutto", ur"arbeiten",
ur"machte", ur"conhecido", ur"eivät", ur"azután", ur"tentaram", ur"tomto", ur"ÎÅÇÏ", ur"houvera", ur"innych", ur"detta", ur"tenidas", ur"τις", ur"regelmäßig",
ur"zur", ur"darunter", ur"morgige", ur"theirs", ur"ÐÅÒÅÄ", ur"o", ur"serás", ur"serán", ur"algo", ur"kellett", ur"ÂÙÌÉ", ur"niin", ur"zum", ur"soc", ur"aber",
ur"sog", ur"fuisteis", ur"drüber", ur"som", ur"nÅ", ur"erre", ur"son", ur"üç", ur"sou", ur"podle", ur"stavamo", ur"soy", ur"varte", ur"jene", ur"dürfte",
ur"novo", ur"hallo", ur"giu", ur"fûmes", ur"तो", ur"avait", ur"habríais", ur"nove", ur"keille", ur"uw", ur"avais", ur"forsÛke", ur"újabb", ur"minusta", ur"tilbake",
ur"éssent", ur"gib", ur"novy", ur"lage", ur"jeśli", ur"wat", ur"was", ur"altijd", ur"podrias", ur"Å", ur"einigen", ur"uten", ur"some", ur"fora", ur"avions",
ur"très", ur"leider", ur"felé", ur"dieselbe", ur"alguno", ur"när", ur"podrian", ur"trug", ur"verdi", ur"hjå", ur"woher", ur"tengan", ur"estiverem", ur"nerde", ur"×ÓÀ",
ur"until", ur"gemacht", ur"sondern", ur"तक", ur"azt", ur"tengas", ur"tenía", ur"zeitweise", ur"facevano", ur"niinä", ur"ça", ur"zudem", ur"cokolwiek", ur"ÍÅÖÄÕ",
ur"gängig", ur"molt", ur"efter", ur"abbiano", ur"habíamos", ur"door", ur"bedarf", ur"ni", ur"allzu", ur"równie¿", ur"no", ur"wollten", ur"na", ur"tivemos", ur"fusses",
ur"when", ur"ne", ur"einstmals", ur"til", ur"ny", ur"wolltet", ur"zelf", ur"tid", ur"zuviel", ur"hát", ur"nu", ur"denn", ur"×ÁÍ", ur"tuyas", ur"ÖÅ", ur"kva",
ur"besteht", ur"dies", ur"lenni", ur"żadnych", ur"havemos", ur"kvi", ur"let's", ur"vår", ur"×ÁÓ", ur"tendremos", ur"quindi", ur"apontar", ur"joita", ur"więcej",
ur"wolltest", ur"bazý", ur"którzy", ur"gängiges", ur"ondan", ur"inkje", ur"sujet", ur"rief", ur"ÂÏÌÅÅ", ur"sicher", ur"oss", ur"weshalb", ur"muss", ur"aurions",
ur"sieht", ur"selbst", ur"sejam", ur"¿e", ur"primer", ur"lungo", ur"macht", ur"by³o", ur"ver", ur"ÞÔÏ", ur"habidas", ur"tust", ur"seither", ur"þuna", ur"quienes",
ur"deswegen", ur"by³a", ur"mache", ur"quasi", ur"by³y", ur"þunu", ur"व", ur"vem", ur"från", ur"fuiste", ur"befragten", ur"ÔÏÔ", ur"éramos", ur"hattet", ur"than",
ur"ihnen", ur"houveria", ur"anfing", ur"hatten", ur"koennen", ur"li", ur"befragter", ur"trabajais", ur"belki", ur"din", ur"estéis", ur"selber", ur"did", ur"die",
ur"warst", ur"dig", ur"ÍÅÎÑ", ur"meille", ur"mehrere", ur"somos", ur"avremo", ur"altý", ur"suoi", ur"prvni", ur"dit", ur"sogar", ur"dir", ur"jedenfalls",
ur"ville", ur"serons", ur"hvem", ur"cosa", ur"ciertas", ur"इसे", ur"einführen", ur"estuvieran", ur"anerkannter", ur"hver", ur"są", ur"versorgen", ur"दिया", ur"trop",
ur"facessi", ur"ÐÒÉ", ur"estou", ur"ausserdem", ur"szerint", ur"sagte", ur"joilla", ur"joille", ur"dem", ur"schätzte", ur"sareste", ur"jährige", ur"pouze", ur"saresti",
ur"serait", ur"ÂÙÌÏ", ur"nimmt", ur"infolge", ur"hadn't", ur"negli", ur"semmi", ur"É", ur"उस", ur"jednak", ur"fuer", ur"tuviéramos", ur"koennt", ur"niistä", ur"akik",
ur"magát", ur"legalább", ur"molts", ur"meillä", ur"molto", ur"molti", ur"bom", ur"bon", ur"wszystkich", ur"deg", ur"molta", ur"keineswegs", ur"keresztül", ur"amely",
ur"bevor", ur"nejsou", ur"hade", ur"hänellä", ur"prawie", ur"ÅÍÕ", ur"till", ur"że", ur"lesen", ur"estuvieras", ur"åt", ur"melyek", ur"pièce", ur"sådana", ur"tages",
ur"ÎÁÄ", ur"ÓÏ×ÓÅÍ", ur"pred", ur"s±", ur"pero", ur"abban", ur"daneben", ur"ये", ur"sofern", ur"konnte", ur"ayante", ur"ÐÏÄ", ur"steige", ur"pres", ur"vous",
ur"eussent", ur"auront", ur"aurons", ur"ook", ur"unsere", ur"siate", ur"एस", ur"unserm", ur"sÅ", ur"ambdós", ur"você", ur"abgerufen", ur"gestern", ur"seremos",
ur"só", ur"muitos", ur"sous", ur"dykk", ur"clanek", ur"schließlich", ur"एक", ur"olimme", ur"så", ur"ihre", ur"fossem", ur"ÞÅÇÏ", ur"tengamos", ur"noch", ur"सभी",
ur"nommés", ur"hayamos", ur"ÍÏÑ", ur"onlarýn", ur"bastante", ur"parce", ur"tuviesen", ur"होने", ur"aquel", ur"nyt", ur"però", ur"korleis", ur"machten", ur"पे",
ur"allerdings", ur"anderer", ur"mas", ur"habremos", ur"erhält", ur"पर", ur"anerkannte", ur"trilyon", ur"tuyos", ur"niemand", ur"aos", ur"bislang", ur"mag",
ur"lidt", ur"lhes", ur"dove", ur"mal", ur"man", ur"sofort", ur"häneen", ur"poikki", ur"deve", ur"geb", ur"devo", ur"avant", ur"su", ur"saranno", ur"το", ur"si",
ur"so", ur"vaya", ur"mange", ur"sa", ur"bardziej", ur"se", ur"τα", ur"contro", ur"täksi", ur"sejamos", ur"eravate", ur"×Ï", ur"hende", ur"immer", ur"facesse",
ur"około", ur"obgleich", ur"stia", ur"×Ù", ur"þeyden", ur"आदि", ur"ved", ur"nimm", ur"mais", ur"he's", ur"habréis", ur"meiste", ur"estarías", ur"अपना", ur"gebracht",
ur"facciate", ur"estuviese", ur"estarían", ur"dieselben", ur"einerseits", ur"jiz", ur"into", ur"nirgendwo", ur"twoje", ur"non", ur"twoja", ur"noi", ur"beim", ur"nog",
ur"aquilo", ur"keitä", ur"अपनी", ur"halb", ur"अपने", ur"hiesige", ur"not", ur"qu", ur"ktoś", ur"trabajamos", ur"nor", ur"nos", ur"ÓÅÂÅ", ur"bearbeitete", ur"avons",
ur"olit", ur"ketä", ur"इसमें", ur"desde", ur"ÓÅÂÑ", ur"anderem", ur"sabeis", ur"kann", ur"el", ur"en", ur"versorgt", ur"reeds", ur"ej", ur"ennek", ur"siihen", ur"eg",
ur"ÓÅÇÏÄÎÑ", ur"ÉÌÉ", ur"había", ur"versorge", ur"houverão", ur"et", ur"wegen", ur"es", ur"er", ur"außer", ur"fôramos", ur"stiano", ur"tuvieseis", ur"meistä",
ur"ponad", ur"ÅÊ", ur"hajam", ur"poco", ur"fazer", ur"bli", ur"valeur", ur"obwohl", ur"ble", ur"voltunk", ur"außen", ur"denselben", ur"geteilte", ur"tienen", ur"punkt",
ur"tuviera", ur"auch", ur"às", ur"terão", ur"czasem", ur"klares", ur"vier", ur"mimo", ur"ora", ur"starebbe", ur"takze", ur"terá", ur"eûmes", ur"×ÄÒÕÇ",
ur"horas", ur"siebte", ur"wichtig", ur"zal", ur"tenir", ur"noget", ur"एवं", ur"ona", ur"teríamos", ur"yourself", ur"belül", ur"sizi", ur"ÇÄÅ", ur"völlig",
ur"behalten", ur"ons", ur"tenim", ur"ένας", ur"nogen", ur"ont", ur"onu", ur"jenem", ur"droite", ur"jenen", ur"anerkannt", ur"ÞÅÒÅÚ", ur"están", ur"ikke", ur"estás",
ur"setzen", ur"nutzen", ur"skal", ur"ähnlich", ur"jenes", ur"jener", ur"vilka", ur"altro", ur"más", ur"sodaß", ur"vort", ur"that", ur"fordert", ur"hun", ur"altre",
ur"laut", ur"padding", ur"qual", ur"quan", ur"bajo", ur"kvifor", ur"jährig", ur"नहीं", ur"podeu", ur"here's", ur"abbiamo", ur"konkrete", ur"έναν", ur"vostre",
ur"birkez", ur"reagiert", ur"pegar", ur"över", ur"houverá", ur"sechs", ur"koennten", ur"suyos", ur"gdzie", ur"avevano", ur"geht", ur"bestehen", ur"stessero",
ur"and", ur"alles", ur"aller", ur"pro", ur"dass", ur"pri", ur"ani", ur"tendrían", ur"sull", ur"azok", ur"ÐÏÔÏÍ", ur"hubiéramos", ur"ans", ur"allen", ur"allem",
ur"sap", ur"miksi", ur"their", ur"dorther", ur"étions", ur"bruke", ur"facessimo", ur"azon", ur"nebo", ur"zog", ur"taka", ur"take", ur"deux", ur"taki",
ur"benim", ur"sect", ur"meglio", ur"soweit", ur"têm", ur"dla", ur"falls", ur"våra", ur"mü", ur"dykkar", ur"ahogy", ur"joksi", ur"einseitige", ur"medan", ur"otuz",
ur"alguna", ur"derjenigen", ur"saremo", ur"heistä", ur"será", ur"alguns", ur"solche", ur"lenne", ur"corrente", ur"seria", ur"estejam", ur"eneste", ur"lassen",
ur"teilte", ur"tínhamos", ur"veröffentlicher", ur"tém", ur"elas", ur"veröffentlichen", ur"estoy", ur"qualquer", ur"bereits", ur"takie", ur"hace", ur"überdies",
ur"sobie", ur"weitere", ur"diz", ur"setzt", ur"siltä", ur"bringen", ur"daar", ur"serais", ur"dich", ur"éppen", ur"jakkolwiek", ur"तरह", ur"only", ur"ε", ur"olisi",
ur"tuviste", ur"hão", ur"aufhören", ur"info", ur"toch", ur"gemäss", ur"ehhez", ur"ÐÏÞÔÉ", ur"nell", ur"wiêc", ur"jó", ur"bylo", ur"keneltä", ur"cannot", ur"fragte",
ur"dasselbe", ur"já", ur"ergänze", ur"primo", ur"sollten", ur"abans", ur"för", ur"leur", ur"byli", ur"amíg", ur"wiewohl", ur"through", ur"where", ur"onlar",
ur"nouveaux", ur"fueran", ur"seas", ur"volna", ur"up", ur"freies", ur"freier", ur"jos", ur"ausgenommen", ur"sean", ur"estamos", ur"vermag", ur"hvorfor", ur"estad",
ur"einst", ur"haja", ur"καθ", ur"και", ur"estan", ur"estat", ur"chaque", ur"estar", ur"svym", ur"utolsó", ur"between", ur"दो", ur"tiverem", ur"podczas", ur"ÉÚ",
ur"ju", ur"tuolle", ur"tut", ur"mellan", ur"tästä", ur"tego", ur"ÉÈ", ur"jo", ur"ÉÍ", ur"ji", ur"como", ur"fez", ur"tuve", ur"je", ur"κατ", ur"come", ur"ja",
ur"koska", ur"ciertos", ur"eröffnen", ur"darin", ur"entweder", ur"avuti", ur"tämä", ur"allo", ur"eröffnet", ur"tous", ur"mand", ur"aura", ur"schnell", ur"quien",
ur"avuto", ur"gjorde", ur"somit", ur"mann", ur"comprido", ur"vuestro", ur"tun", ur"damals", ur"été", ur"hva", ur"devrait", ur"tuo", ur"por", ur"haceis", ur"teillä",
ur"tua", ur"ante", ur"pod", ur"seulement", ur"siete", ur"veröffentlicht", ur"oder", ur"tue", ur"ιαν", ur"aufgrund", ur"kdyz", ur"hepsi", ur"viele",
ur"aquellos", ur"tenían", ur"noen", ur"zpravy", ur"minuun", ur"ceux", ur"hoch", ur"ÏÄÉÎ", ur"those", ur"houverei", ur"myself", ur"κατά", ur"eit", ur"einzig",
ur"minulle", ur"minulla", ur"ergänzte", ur"εις", ur"vaikka", ur"ein", ur"ÄÏ", ur"estávamos", ur"eran", ur"eram", ur"joka", ur"soit", ur"legte",
ur"eras", ur"dört", ur"geehrt", ur"eri", ur"miért", ur"par", ur"pas", ur"yo", ur"επι", ur"einseitig", ur"same", ur"hvilke", ur"jól", ur"otto",
ur"möglich", ur"tout", ur"pak", ur"otte", ur"todos", ur"några", ur"teraz", ur"eitt", ur"zwanzig", ur"persone", ur"sotto", ur"kenenä", ur"algunes", ur"stareste",
ur"entonces", ur"tenha", ur"defa", ur"naszego", ur"hebben", ur"tenho", ur"perché", ur"estivessem", ur"berichtet", ur"noko", ur"tivessem", ur"veröffentlichten",
ur"ausdrückte", ur"veröffentlichtes", ur"machen", ur"can't", ur"noka", ur"então", ur"wessen", ur"siitä", ur"promesso", ur"berichten", ur"konkreter", ur"konkretes",
ur"deze", ur"senken", ur"×", ur"nachdem", ur"being", ur"gdy", ur"keillä", ur"bietet", ur"verdad", ur"át", ur"tuviésemos", ur"þundan", ur"konkreten", ur"quella",
ur"quelle", ur"tim", ur"we've", ur"quelli", ur"quello", ur"jona", ur"vergangene", ur"konnten", ur"abgerufenes", ur"hacemos", ur"którym", ur"onder", ur"avevamo",
ur"ami", ur"ditt", ur"ama", ur"jako", ur"amb", ur"neuen", ur"usamos", ur"mot", ur"neuer", ur"neues", ur"moi", ur"mon", ur"einbaün", ur"tanto", ur"sådan",
ur"वह", ur"serez", ur"darf", ur"już", ur"mod", ur"aurez", ur"acute", ur"eussiez", ur"साथ", ur"ahol", ur"soient", ur"vergangenes", ur"t", ur"où", ur"stava",
ur"ËÁËÁÑ", ur"intet", ur"avrai", ur"debaixo", ur"são", ur"τη", ur"aufzusuchen", ur"nå", ur"bloß", ur"sollen", ur"össze", ur"houveríamos", ur"eddig", ur"geehrte",
ur"naar", ur"blive", ur"avevi", ur"sommes", ur"στις", ur"aż", ur"solltest", ur"besser", ur"meinen", ur"meinem", ur"meiner", ur"meines", ur"tänä", ur"igitt",
ur"heihin", ur"klare", ur"kenen", ur"sarebbe", ur"továbbá", ur"starai", ur"seine", ur"gestrige", ur"fuésemos", ur"secondo", ur"serão", ur"kenet", ur"habe",
ur"siehe", ur"on", ur"om", ur"här", ur"og", ur"of", ur"od", ur"ob", ur"erneut", ur"neden", ur"it's", ur"acz", ur"ou", ur"ÏÐÑÔØ", ur"os", ur"or", ur"op",
ur"seriez", ur"keinä", ur"trabajan", ur"irgendeine", ur"tallä", ur"esses", ur"estés", ur"απ", ur"még", ur"näihin", ur"tuvisteis", ur"darfst",
ur"trabajas", ur"trabajar", ur"het", ur"unas", ur"welches", ur"welcher", ur"hep", ur"how's", ur"her", ur"there", ur"gesagt", ur"tehát", ur"los", ur"több",
ur"ehe", ur"heb", ur"euer", ur"hem", ur"hen", ur"welchem", ur"hei", ur"σε", ur"welchen", ur"tendríais", ur"vÅr", ur"sabemos", ur"eröffne", ur"bunda",
ur"jednakże", ur"gibi", ur"geehrter", ur"gibt", ur"mich", ur"último", ur"with", ur"gängigen", ur"vere", ur"they're", ur"vuestras", ur"wasn't", ur"õ",
ur"agora", ur"saját", ur"sera", ur"voient", ur"we'd", ur"sve", ur"ad", ur"af", ur"ai", ur"hänessä", ur"aj", ur"am", ur"al", ur"ao", ur"an", ur"intenta",
ur"ÔÏ", ur"tengo", ur"saremmo", ur"pourquoi", ur"uit", ur"av", ur"az", ur"tenga", ur"δια", ur"intento", ur"ÄÒÕÇÏÊ", ur"again", ur"estão", ur"wurde", ur"pfui",
ur"missä", ur"pedig", ur"bearbeiteten", ur"gleichwohl", ur"jsem", ur"jses", ur"personnes", ur"starò", ur"eigentlich", ur"woraus", ur"avessero", ur"यदि",
ur"στους", ur"fazia", ur"hubiste", ur"etwas", ur"möglichen", ur"wohlweislich", ur"important", ur"sullo", ur"gängiger", ur"sulla", ur"nutzung", ur"genommen",
ur"ιας", ur"sulle", ur"tenida", ur"ella", ur"tendréis", ur"derzeit", ur"unsen", ur"mellett", ur"unsem", ur"ÍÙ", ur"oraz", ur"eusse", ur"sokat", ur"u",
ur"unser", ur"unses", ur"mías", ur"all", ur"ali", ur"z.B.", ur"ampleamos", ur"ale", ur"noilta", ur"pta", ur"andererseits", ur"ÎÁËÏÎÅÃ", ur"näiltä",
ur"siinä", ur"noissa", ur"ÎÏ", ur"fortsetzt", ur"als", ur"bearbeiten", ur"ÎÉ", ur"müsste", ur"êtes", ur"ty", ur"ÎÁ", ur"tu", ur"gegeben", ur"ÎÅ", ur"to",
ur"niiltä", ur"lavoro", ur"derselbe", ur"maioria", ur"ti", ur"umso", ur"kvar", ur"te", ur"dlatego", ur"ÒÁÚ×Å", ur"ta", ur"faz", ur"estando", ur"über",
ur"estaba", ur"very", ur"fas", ur"wohin", ur"sono", ur"verdadeiro", ur"fan", ur"hinein", ur"te¿", ur"való", ur"żadna", ur"tuvimos", ur"strana", ur"yetmiþ",
ur"żadne", ur"tät", ur"sant", ur"könnten", ur"anar", ur"sans", ur"sollte", ur"sinulla", ur"hendes", ur"joista", ur"sinulle", ur"teneis", ur"hattest",
ur"habré", ur"largo", ur"étés", ur"ecco", ur"habrá", ur"i'll", ur"twoim", ur"tej", ur"tem", ur"ten", ur"immerhin", ur"facevi", ur"faites", ur"kunnen",
ur"unmöglichen", ur"tes", ur"teu", ur"what", ur"sekiz", ur"tú", ur"hänestä", ur"sua", ur"mindig", ur"suo", ur"sul", ur"egyes", ur"sui", ur"letze",
ur"sus", ur"sur", ur"deles", ur"aby", ur"közül", ur"jede", ur"vamos", ur"stavi", ur"neni", ur"ÂÕÄÔÏ", ur"aquells", ur"habiendo", ur"einigermaßen", ur"seiten",
ur"quieto", ur"kimi", ur"ggf", ur"niiksi", ur"hast", ur"meisten", ur"guten", ur"hadde", ur"kime", ur"egész", ur"à", ur"avessi", ur"stavo", ur"meist", ur"avesse",
ur"when's", ur"unbedingt", ur"ÉÎÏÇÄÁ", ur"durch", ur"senden", ur"seréis", ur"hänelle", ur"zawsze", ur"joihin", ur"vid", ur"forderte", ur"vil", ur"την",
ur"habíais", ur"करते", ur"otros", ur"hogy", ur"nokre", ur"fueras", ur"hvordan", ur"minussa", ur"tutti", ur"etc", ur"wiele", ur"jejich", ur"trabaja", ur"houver",
ur"folgende", ur"seras", ur"darum", ur"रखें", ur"wielu", ur"trabajo", ur"more", ur"mellom", ur"þeyi", ur"milyon", ur"noina", ur"noille", ur"hubieras", ur"obok",
ur"kenestä", ur"schlechter", ur"potser", ur"få", ur"ÄÁ", ur"według", ur"bizden", ur"unmögliche", ur"noilla", ur"tähän", ur"करता", ur"teistä", ur"muze",
ur"nerede", ur"stiate", ur"der", ur"des", ur"det", ur"minut", ur"ÜÔÏÔ", ur"της", ur"dei", ur"minhas", ur"fomos", ur"del", ur"fÅ", ur"den", ur"tuas", ur"bunun",
ur"teille", ur"beitragen", ur"wieder", ur"sois", ur"erhielt", ur"iniciar", ur"lichten", ur"ÎÁÓ", ur"seríais", ur"też", ur"zumal", ur"sense", ur"mehr", ur"उनका",
ur"gratulierte", ur"avemmo", ur"sitt", ur"folgender", ur"étant", ur"können", ur"gewissermaßen", ur"voltak", ur"before", ur"vorbei", ur"nagyobb", ur"jährigen",
ur"twym", ur"másik", ur"fu", ur"gängige", ur"yedi", ur"ÅÅ", ur"notre", ur"vosaltres", ur"fa", ur"tuona", ur"numa", ur"não", ur"fi", ur"versorgtes", ur"teile",
ur"ËÁËÏÊ", ur"a", ur"egy", ur"estuviéramos", ur"kein", ur"उनके", ur"abgerufene", ur"proto", ur"unterhalb", ur"ÄÌÑ", ur"dentro", ur"या", ur"milyar", ur"ise",
ur"यह", ur"verrieten", ur"ferner", ur"mezi", ur"लिये", ur"that's", ur"don't", ur"sämtliche", ur"consigueix", ur"något", ur"zugleich", ur"hayáis", ur"pana",
ur"quelles", ur"bloss", ur"està", ur"pani", ur"its", ur"utána", ur"está", ur"allg", ur"alle", ur"alla", ur"sopra", ur"joissa", ur"sinusta", ur"teidän",
ur"hubiésemos", ur"voran", ur"allt", ur"teidät", ur"nimmer", ur"hvor", ur"nossos", ur"ÍÏÖÅÔ", ur"haven't", ur"musste", ur"müssen", ur"ya", ur"consigo",
ur"mitkä", ur"ces", ur"you've", ur"ją", ur"tragen", ur"dnes", ur"abgerufener", ur"tausend", ur"mussten", ur"tuoi", ur"solange", ur"næsten", ur"ilyenkor",
ur"tuvieran", ur"fünf", ur"würden", ur"tra", ur"denne", ur"hvis", ur"denna", ur"inclòs", ur"vannak", ur"isn't", ur"nein", ur"staresti", ur"tuosta",
ur"stemmo", ur"hubieseis", ur"nossa", ur"möglicher", ur"teníamos", ur"ugyanis", ur"sagtest", ur"todo", ur"nosso", ur"somente", ur"einem", ur"houvemos",
ur"serions", ur"nuovo", ur"tenido", ur"nuovi", ur"ÎÕ", ur"buono", ur"ÔÁÍ", ur"jolle", ur"seáis", ur"they'll", ur"jolla", ur"estaremos", ur"lehet", ur"mukaan",
ur"dehors", ur"gefiel", ur"fecero", ur"puc", ur"verdade", ur"hiszen", ur"jakiż", ur"asi", ur"ÎÅÔ", ur"enquanto", ur"bekannter", ur"blieb", ur"jähriges",
ur"estada", ur"kon", ur"dabei", ur"voor", ur"हुए", ur"nosotros", ur"kimden", ur"हुई", ur"w", ur"estejamos", ur"tivesse", ur"हुआ", ur"jakiś", ur"mindenki",
ur"hubiera", ur"dina", ur"onlari", ur"nach", ur"étants", ur"blitt", ur"tuvieras", ur"tedy", ur"cada", ur"donc", ur"dins", ur"étante", ur"jer", ur"tato", ur"kom",
ur"seksen", ur"teissä", ur"nome", ur"esas", ur"avec", ur"przez", ur"avez", ur"contra", ur"przed", ur"ÔÏÌØËÏ", ur"jeg", ur"jed", ur"jej", ur"jen",
ur"dlaczego", ur"wenigstens", ur"míos", ur"para", ur"jego", ur"teitä", ur"part", ur"darüber", ur"tive", ur"schon", ur"tak¿e", ur"ÐÏÓÌÅ", ur"musst", ur"aan",
ur"dans", ur"इस", ur"dann", ur"sillä", ur"dank", ur"seamos", ur"teve", ur"maga", ur"birþeyi", ur"überall", ur"teriam", ur"heiltä", ur"vielmals", ur"schreibens",
ur"ebenfalls", ur"aussi", ur"tiver", ur"svych", ur"benne", ur"oda", ur"elõször", ur"pomimo", ur"eingesetzt", ur"için", ur"anerkanntes", ur"sånn", ur"adesso",
ur"invece", ur"sizden", ur"euch", ur"faccia", ur"später", ur"lik", ur"also", ur"zwölf", ur"näinä", ur"estuviesen", ur"quattro", ur"nuestras", ur"selv", ur"habrán",
ur"jakie", ur"such", ur"tentar", ur"ÅÓÌÉ", ur"dokuz", ur"any", ur"tuvo", ur"kan", ur"kam", ur"essa", ur"mely", ur"esse", ur"starteten", ur"tivera",
ur"bzw", ur"ke", ur"sehr", ur"minha", ur"meine", ur"ki", ur"varför", ur"hubieses", ur"swoje", ur"jeżeli", ur"ËÔÏ", ur"ansetzen", ur"stessimo", ur"wieso", ur"aztán",
ur"fosse", ur"haar", ur"sobą", ur"unseres", ur"unserer", ur"tener", ur"új", ur"tinha", ur"fino", ur"font", ur"unseren", ur"fôssemos", ur"में",
ur"quem", ur"quel", ur"mina", ur"INSERmi", ur"irgend", ur"από", ur"στην", ur"fareste", ur"valami", ur"hatte", ur"svymi", ur"porque", ur"minun", ur"steste",
ur"गया", ur"algún", ur"esteja", ur"×ÏÔ", ur"vorgestern", ur"timto", ur"fûtes", ur"étée", ur"they'd", ur"mío", ur"bedurfte", ur"stando", ur"during", ur"hij",
ur"podeis", ur"him", ur"hin", ur"direkt", ur"ÏÎ", ur"fussent", ur"ÏÂ", ur"vilket", ur"schätzten", ur"etter", ur"vissza", ur"ÏÔ", ur"koennte", ur"seu",
ur"सकता", ur"ses", ur"ser", ur"होती", ur"forderten", ur"fuesen", ur"होते", ur"seg", ur"fueses", ur"vorne", ur"bare", ur"are", ur"sea", ur"sen", ur"llavors",
ur"tohle", ur"sei", ur"einführten", ur"fand", ur"varje", ur"ktery", ur"vont", ur"irgendwer", ur"ktera", ur"consecutivo", ur"estará", ur"consecutivi", ur"kteri",
ur"dein", ur"deim", ur"solo", ur"soll", ur"dalla", ur"jeden", ur"jedem", ur"dalle", ur"ebenso", ur"ncht", ur"solc", ur"ÔÒÉ", ur"ison", ur"estivemos", ur"trage",
ur"altmýþ", ur"hiç", ur"jedes", ur"jeder", ur"iki", ur"ligado", ur"sols", ur"both", ur"fortsetzen", ur"avesti", ur"wouldn't", ur"etliche", ur"yüz",
ur"angesetzter", ur"számára", ur"होता", ur"ÞÕÔØ", ur"सकते", ur"dadurch", ur"aveste", ur"cierto", ur"samma", ur"nter", ur"sonstwo", ur"était", ur"samme",
ur"olla", ur"pessoas", ur"इसका", ur"zpet", ur"cierta", ur"ÞÅÍ", ur"avrò", ur"estivesse", ur"auriez", ur"zusammen", ur"dizer", ur"moins", ur"arbeid", ur"fummo",
ur"estuvisteis", ur"न", ur"tälle", ur"weder", ur"due", ur"allmählich", ur"whom", ur"Ë", ur"forrige", ur"rett", ur"txt", ur"ollut", ur"dus", ur"po", ur"lett",
ur"ÍÎÅ", ur"fire", ur"what's", ur"stattdessen", ur"amelyeket", ur"gar", ur"johon", ur"estuvierais", ur"heute", ur"gab", ur"सबसे", ur"fut", ur"अभी", ur"ez",
ur"×ÓÅ", ur"irgendwo", ur"sizin", ur"fossimo", ur"इसकी", ur"fue", ur"इसके", ur"möchten", ur"mögliche", ur"fui", ur"alatt", ur"ketkä", ur"vom", ur"von",
ur"étaient", ur"voi", ur"hänet", ur"itself", ur"vor", ur"pÅ", ur"zieht", ur"nós", ur"triplo", ur"voy", ur"beiderlei", ur"steht", ur"pela", ur"acaba",
ur"direita", ur"fueron", ur"på", ur"estes", ur"atrás", ur"utan", ur"esteu", ur"które", ur"ktere", ur"keiden", ur"warum", ur"która", ur"tellement", ur"zwar",
ur"geweest", ur"eues", ur"eure", ur"joilta", ur"neuem", ur"keine", ur"cikkeket", ur"który", ur"elsõ", ur"obschon", ur"entre", ur"hinterher", ur"noiksi",
ur"tengáis", ur"hago", ur"szét", ur"estuvieses", ur"eles", ur"senkten", ur"õk", ur"y", ur"ËÏÇÄÁ", ur"kívül", ur"konkret", ur"incluso", ur"eigenen",
ur"rechts", ur"tych", ur"fÛrst", ur"kenelle", ur"stesso", ur"mie", ur"freie", ur"nuestra", ur"mo¿na", ur"vielleicht", ur"amp", ur"eigenes", ur"mitä",
ur"ÓËÁÚÁÌ", ur"nuestro", ur"bliver", ur"finden", ur"mintha", ur"vagyis", ur"gueno", ur"kven", ur"danke", ur"arriba", ur"tus", ur"findet", ur"acerca",
ur"keihin", ur"durften", ur"cui", ur"bin", ur"emme", ur"wil", ur"bij", ur"lehetett", ur"womit", ur"folgenden", ur"aviez", ur"bé", ur"Ï", ur"habida",
ur"hayas", ur"biz", ur"żeby", ur"jste", ur"bir", ur"bis", ur"habido", ur"weiß", ur"facciamo", ur"d", ur"erste", ur"houveram", ur"jota", ur"valamint",
ur"een", ur"sokkal", ur"trabalho", ur"sehrwohl", ur"mycket", ur"folglich", ur"wir", ur"mögen", ur"sue", ur"estaríais", ur"kenellä", ur"hinten", ur"bowiem",
ur"hinter", ur"aquell", ur"allgemein", ur"bastant", ur"ilyen", ur"aquele", ur"nÅr", ur"ourselves", ur"aquela", ur"beträchtlich", ur"minulta", ur"terei",
ur"néhány", ur"peu", ur"depuis", ur"per", ur"poza", ur"estivera", ur"pelo", ur"bêdzie", ur"inicio", ur"czasami", ur"desligado", ur"proc", ur"ÔÁË", ur"be",
ur"nello", ur"acht", ur"nella", ur"siendo", ur"bo", ur"nelle", ur"avresti", ur"bu", ur"mutta", ur"weil", ur"bezüglich", ur"nosotras", ur"by", ur"υπό",
ur"être", ur"juste", ur"wenngleich", ur"bist", ur"darauf", ur"promeiro", ur"daraus", ur"ide", ur"benden", ur"yli", ur"inte", ur"allora", ur"ÐÏÔÏÍÕ",
ur"teniendo", ur"steigt", ur"będą", ur"diesseits", ur"gewesen", ur"kanssa", ur"vaan", ur"because", ur"fordern", ur"empleais", ur"przecież", ur"neki",
ur"poden", ur"podem", ur"degli", ur"fossero", ur"keneksi", ur"ezek", ur"avremmo", ur"fast", ur"häntä", ur"suis", ur"längstens", ur"liegt", ur"we're",
ur"aufgehört", ur"besonders", ur"fortsetzten", ur"atras", ur"poder", ur"ca.", ur"somme", ur"himself", ur"estabais", ur"derart", ur"collapsed",
ur"napiste", ur"voltam", ur"comprare", ur"ÞÔÏÂÙ", ur"habidos", ur"były", ur"sowohl", ur"å", ur"możliwe", ur"uz", ur"nasýl", ur"ut", ur"schwierig",
ur"bizim", ur"hasn't", ur"cikk", ur"leicht", ur"um", ur"majd", ur"un", ur"द्वारा", ur"było", ur"doc", ur"była", ur"ud", ur"z", ur"nogle", ur"befragte",
ur"titel", ur"कुल", ur"tiveram", ur"seront", ur"ÅÇÏ", ur"teilten", ur"as", ur"कुछ", ur"mochte", ur"nad", ur"fossi", ur"elles", ur"eller", ur"demnach",
ur"beide", ur"wollte", ur"nam", ur"nas", ur"nich", ur"hubiesen", ur"ellen", ur"hanem", ur"toho", ur"siden", ur"temos", ur"lediglich", ur"eurer", ur"eures",
ur"olleet", ur"consigueixen", ur"dall", ur"wohl", ur"aveva", ur"dalt", ur"derselben", ur"jakichś", ur"egyéb", ur"euren", ur"consigueixes", ur"eurem",
ur"habrías", ur"langsam", ur"lang", ur"glücklicherweise", ur"agl", ur"e", ur"vice", ur"tämän", ur"muchos", ur"gehen", ur"she'd", ur"teto", ur"she's",
ur"tendría", ur"nasi", ur"having", ur"once", ur"benutzt", ur"noiden", ur"oberhalb", ur"dannen", ur"eûtes", ur"ganz", ur"sitta", ur"essas", ur"farò",
ur"heutige", ur"będzie", ur"setzte", ur"essai", ur"ge", ur"unes", ur"go", ur"επ", ur"dagegen", ur"katrilyon", ur"zogen", ur"seni", ur"ÜÔÏÍ", ur"keneen",
ur"lille", ur"könnte", ur"entsprechend", ur"sarei", ur"sooft", ur"nuestros", ur"sieben", ur"tyto", ur"talán", ur"übrigens", ur"és", ur"wszystkim",
ur"tivermos", ur"tuto", ur"wszystkie", ur"maar", ur"eso", ur"naszych", ur"mustn't", ur"yourselves", ur"sinä", ur"möchtest", ur"εξ", ur"vos", ur"εκ",
ur"també", ur"onlardan", ur"tre", ur"they've", ur"ÐÏ", ur"roku", ur"általában", ur"bleiben", ur"niitä", ur"ÔÁËÏÊ", ur"él", ur"starebbero",
ur"nuo", ur"zo", ur"you'd", ur"fus", ur"gratulieren", ur"ze", ur"vele", ur"direkte", ur"za", ur"ÓËÁÚÁÌÁ", ur"gmbh", ur"στη", ur"στα", ur"någon",
ur"zu", ur"teljes", ur"στο", ur"übermorgen", ur"folk", ur"zapewne", ur"sinussa", ur"õket", ur"eurent", ur"unserem", ur"deras", ur"unmöglich", ur"biri",
ur"gÅ", ur"einige", ur"indem", ur"wachen", ur"tivéramos", ur"tened", ur"ÎÉÞÅÇÏ", ur"cela", ur"έσα", ur"saps", ur"sí", ur"lei", ur"się", ur"quels",
ur"mikä", ur"kannst", ur"étais", ur"les", ur"tendrá", ur"cuando", ur"mnie", ur"gedurft", ur"sind", ur"sine", ur"bedürfen", ur"sina", ur"honom",
ur"avreste", ur"egyre", ur"olyan", ur"dell", ur"tegen", ur"gleichzeitig", ur"ersten", ur"erster", ur"nær", ur"रहे", ur"niets", ur"avendo", ur"ovat",
ur"mentre", ur"wie", ur"रहा", ur"hennes", ur"amelynek", ur"wij", ur"että", ur"volt", ur"veröffentlichte", ur"últim", ur"zijn", ur"mens", ur"meihin",
ur"viszont", ur"toteż", ur"dreißig", ur"from", ur"che", ur"usa", ur"uso", ur"chi", ur"fel", ur"fem", ur"gern", ur"usw", ur"few", ur"feu", ur"fer",
ur"kuin", ur"kunde", ur"fuese", ur"mindent", ur"siê", ur"themselves", ur"zij", ur"faresti", ur"fai", ur"fará", ur"farà", ur"wurden", ur"didn't",
ur"estarás", ur"azért", ur"Ñ", ur"unterbrach", ur"ette", ur"jeste", ur"olivat", ur"startet", ur"vuestra", ur"farebbe", ur"sembrava", ur"joiksi",
ur"this", ur"siksi", ur"nekem", ur"pour", ur"ÇÏ×ÏÒÉÌ", ur"jakoś", ur"dritte", ur"sabe", ur"jeho", ur"votre", ur"faceste", ur"noita", ur"links",
ur"heidät", ur"caminho", ur"slik", ur"tüm", ur"beni", ur"heidän", ur"his", ur"zwischen", ur"tal", ur"tam", ur"seriam", ur"gefälligst", ur"tak",
ur"keinerlei", ur"usais", ur"sobald", ur"sit", ur"siz", ur"syv", ur"mein", ur"tai", ur"gratuliert", ur"sia", ur"diejenige", ur"sig", ur"fuéramos",
ur"sie", ur"cual", ur"delas", ur"itse", ur"sin", ur"einig", ur"fare", ur"hubisteis", ur"ËÏÎÅÞÎÏ", ur"klar", ur"facevate", ur"estivéssemos",
ur"amelyet", ur"ausdrücken", ur"frau", ur"stesti", ur"hän", ur"×ÐÒÏÞÅÍ", ur"estivéramos", ur"hätten", ur"tenéis", ur"eher", ur"ÔÅÍ", ur"isso",
ur"ÔÙ", ur"worin", ur"कहा", ur"waere", ur"primero", ur"insofern", ur"subito", ur"olisitte", ur"sido", ur"eröffnete", ur"azonban", ur"comme", ur"own",
ur"won't", ur"ÓÏ", ur"da?", ur"míg", ur"znowu", ur"volte", ur"le", ur"la", ur"eue", ur"lo", ur"byt", ur"stanno", ur"før", ur"demselben", ur"aucuns",
ur"byl", ur"eux", ur"eut", ur"dess", ur"facevo", ur"lecz", ur"morgen", ur"erhielten", ur"waren", ur"tatsächlichen", ur"dal", ur"wäre", ur"dan", ur"danken",
ur"dai", ur"devem", ur"dat", ur"doch", ur"wolle", ur"das", ur"qué", ur"quê", ur"natomiast", ur"stette", ur"ÂÏÌØÛÅ", ur"komme", ur"stetti", ur"irgendwen",
ur"eben", ur"tras", ur"kommt", ur"modo", ur"solches", ur"riktig", ur"bearbeite", ur"houveriam", ur"ÎÅÊ", ur"habría", ur"doing", ur"mijn", ur"ÎÅÅ",
ur"tente", ur"fortsetzte", ur"wszyscy", ur"our", ur"beginnen", ur"tento", ur"solchen", ur"solchem", ur"out", ur"böden", ur"tuya", ur"kiedy", ur"là",
ur"début", ur"tohoto", ur"sugl", ur"werdet", ur"tuyo", ur"ÐÒÏ", ur"your", ur"aquelles", ur"mate", ur"minkä", ur"omdat", ur"pan", ur"करें", ur"bekennen",
ur"fuerais", ur"faceva", ur"heillä", ur"eravamo", ur"meiltä", ur"versorgte", ur"näille", ur"tempo", ur"vergangen", ur"formos", ur"qua", ur"ill.", ur"τους",
ur"næste", ur"que", ur"kommen", ur"kaum", ur"qui", ur"fuimos", ur"hänen", ur"ÂÙ", ur"milyen", ur"tatsächliches", ur"tatsächlicher", ur"heraus", ur"eens",
ur"ono", ur"innen", ur"deshalb", ur"daß", ur"fait", ur"nachhinein", ur"tomuto", ur"ihr", ur"furono", ur"sjøl", ur"और", ur"powinien",
ur"suya", ur"damit", ur"vergangener", ur"illetve", ur"ihm", ur"był", ur"you're", ur"ÏÎÉ", ur"haya", ur"ÚÁÞÅÍ", ur"ÏÎÁ", ur"estemos", ur"wodurch",
ur"starete", ur"mo¿e", ur"which", ur"abbia", ur"millä", ur"aufhörte", ur"plupart", ur"haver", ur"blivit", ur"fût", ur"bude", ur"ÞÅÌÏ×ÅË", ur"quando", ur"ebbero",
ur"jenseits", ur"too", ur"być", ur"brachte", ur"algunas", ur"herself", ur"sicherlich", ur"sinuun", ur"bei", ur"ben", ur"weren't", ur"bem", ur"quanti", ur"sok",
ur"bez", ur"num", ur"których", ur"azzal", ur"encore", ur"seinem", ur"seinen", ur"elég", ur"ÎÉËÏÇÄÁ", ur"ÔÕÔ", ur"heitä", ur"eusses", ur"blir", ur"have",
ur"manchmal", ur"båe", ur"sem", ur"seiner", ur"seines", ur"ista", ur"itt", ur"mij", ur"iste", ur"mio", ur"min", ur"mia", ur"ÂÙÔØ", ur"fussiez",
ur"während", ur"mig", ur"isto", ur"veel", ur"को", ur"übrig", ur"beinahe", ur"के", ur"mir", ur"mit", ur"intentais", ur"कि", ur"का", ur"empleo", ur"tältä",
ur"dette", ur"कर", ur"senke", ur"where's", ur"jemand", ur"nous", ur"sedan", ur"sist", ur"heissä", ur"why", ur"senkt", ur"ingi", ur"veya",
ur"cima", ur"været", ur"nutzt", ur"muessen", ur"you'll", ur"beþ", ur"कई", ur"ÎÅÌØÚÑ", ur"tuotä", ur"így", ur"gdziekolwiek", ur"जैसे", ur"muy", ur"serías",
ur"nagy", ur"ismét", ur"niet", ur"zuerst", ur"×ÓÅÈ", ur"ÅÓÔØ", ur"soyez", ur"sådant", ur"dunklen", ur"moet", ur"facevamo", ur"should", ur"nereye", ur"w³a¶nie",
ur"there's", ur"jak", ur"forem", ur"noin", ur"sonst", ur"intentamos", ur"ayez", ur"begonnen", ur"podia", ur"joina", ur"sinun", ur"deine", ur"sinua",
ur"avete", ur"ËÕÄÁ", ur"autor", ur"wordt", ur"Ó", ur"tilstand", ur"etwa", ur"nacher", ur"sinut", ur"aquí", ur"viel", ur"keiner", ur"keines", ur"ganzem",
ur"estaré", ur"ganzen", ur"seitdem", ur"στον", ur"gbr", ur"she", ur"ganzes", ur"ganzer", ur"keinem", ur"keinen", ur"muj", ur"×ÓÅÇÏ", ur"währenddessen",
ur"aquelas", ur"stets", ur"gefallen", ur"seite", ur"vært", ur"direkten", ur"podriamos", ur"soprattutto", ur"neben", ur"unnötig", ur"være", ur"schreibe",
ur"ert", ur"ponieważ", ur"miei", ur"wird", ur"statt", ur"seht", ur"ÓÁÍ", ur"setzten", ur"hiermit", ur"facciano", ur"berichtete", ur"below", ur"tene",
ur"tuvieron", ur"lub", ur"sehe", ur"byla", ur"nossas", ur"stato", ur"lui", ur"ús", ur"stati", ur"wollen", ur"houveremos", ur"olisivat", ur"moim",
ur"kei", ur"faremo", ur"tema", ur"trabalhar", ur"einfach", ur"dallo", ur"tat", ur"tentei", ur"ende", ur"kez", ur"avuta", ur"avute", ur"ets", ur"aqui",
ur"ett", ur"soeben", ur"è", ur"से", ur"conseguim", ur"conseguir", ur"también", ur"doksan", ur"houvessem", ur"möchte", ur"s", ur"suchen",
ur"ci", ur"co", ur"author", ur"sangen", ur"bsp.", ur"ca", ur"sitä", ur"étées", ur"ce", ur"trzeba", ur"cz", ur"ÄÁÖÅ", ur"ab", ur"heeft", ur"muesst",
ur"ÜÔÕ", ur"havde", ur"durfte", ur"niihin", ur"estaría", ur"aczkolwiek", ur"tiene", ur"he'd", ur"själv", ur"geehrten", ur"zehn", ur"jsou", ur"sara",
ur"farai", ur"keiksi", ur"faccio", ur"estén", ur"vors", ur"tenidos", ur"estava", ur"igen", ur"natürlich", ur"houverem", ur"allerlei", ur"estáis",
ur"alsbald", ur"queste", ur"aquellas", ur"c", ur"meus", ur"siamo", ur"sollst", ur"uns", ur"derartig", ur"ours", ur"jobban", ur"könn", ur"ott",
ur"estuvimos", ur"facessero", ur"indessen", ur"hubo", ur"tivéssemos", ur"é", ur"umas", ur"hube", ur"will", ur"estiver", ur"keiltä", ur"au",
ur"vilkas", ur"leer", ur"ill", ur"at", ur"kuka", ur"va", ur"questo", ur"ve", ur"letztens", ur"vi", ur"ÈÏÔØ", ur"längst", ur"ziehen", ur"nincs",
ur"vu", ur"nützt", ur"angesetzten", ur"mesmo", ur"sowie", ur"þunda", ur"parte", ur"δι", ur"sarà", ur"ÞÔÏÂ", ur"ju¿", ur"vore", ur"noe", ur"ergänzten",
ur"fleste", ur"nächste", ur"nada", ur"une", ur"tiempo", ur"näillä", ur"bald", ur"näistä", ur"tuohon", ur"essendo", ur"pelos", ur"estado",
ur"starà", ur"sugli", ur"soviel", ur"i", ur"serían", ur"ÕÖ", ur"avevate", ur"these", ur"estuviésemos", ur"oft", ur"mÅte", ur"senza", ur"terzo",
ur"uno", ur"bekannte", ur"onde", ur"emplean", ur"lesz", ur"ÒÁÚ", ur"empleas", ur"emplear", ur"avrà", ur"nosaltres", ur"meissä", ur"jeji", ur"कहते",
ur"weg", ur"przede", ur"çok", ur"estaríamos", ur"vÖre", ur"getan", ur"wen", ur"wem", ur"wel", ur"gleich", ur"wer", ur"habríamos", ur"werd", ur"protoze",
ur"vÖrt", ur"houvermos", ur"gute", ur"ought", ur"sich", ur"mis", ur"amit", ur"haut", ur"लिए", ur"þu", ur"jonka", ur"został", ur"ayant", ur"niillä",
ur"þeyler", ur"you", ur"houvesse", ur"estarán", ur"budes", ur"kilka", ur"hubimos", ur"like", ur"×ÓÅÇÄÁ", ur"dennoch", ur"spielen", ur"cikkek",
ur"olitte", ur"mía", ur"vermutlich", ur"sagen", ur"jedoch", ur"teremos", ur"unterbrechen", ur"hossen", ur"budem", ur"why's", ur"kdo", ur"irgendwie",
ur"mihin", ur"schätzen", ur"otras", ur"kde", ur"vosotros", ur"ktokolwiek", ur"lagen", ur"jotka", ur"shan't", ur"csak", ur"est", ur"zwei", ur"dagl",
ur"fanno", ur"kleinen", ur"doen", ur"stieg", ur"kleines", ur"kleiner", ur"bardzo", ur"does", ur"esa", ur"między", ur"olin", ur"sette", ur"estic",
ur"erais", ur"teihin", ur"puedo", ur"usan", ur"hajamos", ur"ÅÝÅ", ur"mitt", ur"fordi", ur"puede", ur"agli", ur"ayons", ur"oben", ur"hoss", ur"usas",
ur"usar", ur"niille", ur"after", ur"vosotras", ur"about", ur"também", ur"anden", ur"estábamos", ur"daran", ur"lhe", ur"ander", ur"hier", ur"andet",
ur"irgendwas", ur"em", ur"wszystko", ur"eins", ur"ÎÁÄÏ", ur"solcher", ur"mert", ur"ön", ur"teus", ur"più", ur"donde", ur"eine", ur"ÔÏÍ", ur"ei",
ur"mere", ur"wollt", ur"jine", ur"है", ur"हो", ur"vai", ur"van", ur"vam", ur"ही", ur"vad", ur"quante", ur"eussions", ur"quanta", ur"ed", ur"var", ur"vas",
ur"quanto", ur"når", ur"hvornår", ur"Ó×ÏÀ", ur"faranno", ur"persze", ur"i've", ur"haette", ur"andernfalls", ur"but", ur"kenessä", ur"ho", ur"farete", ur"ha",
ur"ultimo", ur"geblieben", ur"he", ur"ezért", ur"davor", ur"néha", ur"seit", ur"dagli", ur"houvéramos", ur"znów", ur"j", ur"ÕÖÅ", ur"zufolge", ur"wär", ur"olemme",
ur"seid", ur"sein", ur"davon", ur"hvad", ur"braucht", ur"stesse", ur"povo", ur"vuestros", ur"amelyek", ur"innerhalb", ur"ins", ur"vostri", ur"inn", ur"überallhin",
ur"jag", ur"vostro", ur"ind", ur"vostra", ur"dalsi", ur"mye", ur"piu", ur"aies", ur"arra", ur"tendrán", ur"deires", ur"siano", ur"other", ur"seus", ur"disse",
ur"prave", ur"sarete", ur"tenhamos", ur"også", ur"után", ur"fois", ur"hubieron", ur"quarto", ur"ese", ur"müßte", ur"há", ur"stai", ur"reagierte", ur"ÎÉÈ",
ur"trotzdem", ur"ogsÅ", ur"ÎÉÍ", ur"pode", ur"außerdem", ur"estuviste", ur"Ä×Á", ur"allein", ur"mistä"])

