apiVersion: apps/v1
kind: Deployment
metadata:
  name: exareme-keystore-deployment
  labels:
    app: exareme-keystore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exareme-keystore
  template:
    metadata:
      labels:
        app: exareme-keystore
    spec:
      nodeSelector:
        master: "true"
      containers:
      - name: exareme-keystore
        image: bitnami/consul:1.8.3
        ports:
          - containerPort: 8500
        env:
        - name: CONSUL_AGENT_MODE
          value: "server"
        - name: CONSUL_BOOTSTRAP_EXPECT
          value: "1"
        - name: CONSUL_CLIENT_LAN_ADDRESS
          value: "0.0.0.0"
        - name: CONSUL_ENABLE_UI
          value: "true"
      

---

apiVersion: v1
kind: Service
metadata:
  name: exareme-keystore-service
spec:
  type: LoadBalancer
  selector:
    app: exareme-keystore
  ports:
    - protocol: TCP
      port: 8500
      targetPort: 8500
#      nodePort: 30050 # Used for debugging
