---
- name: Find Leader
  shell: docker node ls -f "role=manager" --format '{{ "{{" }}.Hostname {{ "}}" }}'
  register: leader
  tags:
    - always

- name: Find Stacks
  shell: docker stack ls --format '{{ "{{" }}.Name{{ "}}" }}'
  register: nodeStacks
  tags:
    - exareme

- name: Remove Exareme
  shell: docker stack rm "{{ item }}"
  with_items:
    - "{{ nodeStacks.stdout_lines }}"
  ignore_errors: true
  tags:
    - exareme

- name: Find Portainer service ID
  shell: docker service inspect -f '{{ "{{" }}.ID{{ "}}" }}' {{ PORTAINER_NAME }}
  register: portainerID
  ignore_errors: true
  tags:
    - portainer

- name: Remove Portainer
  shell: docker service rm {{ portainerID.stdout }}
  register: portainer_rm
  ignore_errors: true
  tags:
    - portainer
